language: python
python:
    - "3.4"
install: 
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
    - sudo apt-get update -q
    - sudo apt-get install python3-dev 
    - sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps xterm libqt5svg5-dev qttools5-dev qtscript5-dev qtdeclarative5-folderlistmodel-plugin qtdeclarative5-controls-plugin -y 
    - sudo apt-get install postgresql-server-dev-all 
    - sudo apt-get install postgresql-client-common
    - sudo apt-get install libpq-dev 
    - pip install psycopg2
    - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.16/sip-4.16.tar.gz
    - tar -xzf sip-4.16.tar.gz
    - cd sip-4.16
    - python configure.py
    - make -j5
    - sudo make install
    - cd -
    - wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3/PyQt-gpl-5.3.tar.gz
    - tar -xzf PyQt-gpl-5.3.tar.gz
    - cd PyQt-gpl-5.3
    - python configure.py -q /usr/lib/x86_64-linux-gnu/qt5/bin/qmake --confirm-license --enable QtCore --enable QtGui --enable QtTest --enable QtWidgets
    - make -j5
    - sudo make install
    - cd -
    - pip install coveralls
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script: 
    - coverage run ./expert_test.py -a 78.107.239.213:54321
after_success:
    - coveralls
notifications:
      email: false
