INSERT INTO function VALUES (1, 'трапеция');
INSERT INTO hedge VALUES (1, 'не', '1-x');
INSERT INTO hedge VALUES (2, 'очень', 'x^2');
INSERT INTO variable VALUES (1, 'возраст', 0, 100);
INSERT INTO term VALUES (1, 'молодой', 1, '15:20:25:30');
INSERT INTO term VALUES (2, 'старый', 1, '60:65:80:85');
INSERT INTO variable_term VALUES (1, 1);
INSERT INTO variable_term VALUES (1, 2);
INSERT INTO variable_hedge VALUES (1, 1);
INSERT INTO variable_hedge VALUES (1, 2);
INSERT INTO type VALUES (1, 'term');
INSERT INTO type VALUES (2, 'hedge');
INSERT INTO type VALUES (3, 'variable');
INSERT INTO type VALUES (4, 'term_complex');
INSERT INTO type VALUES (5, 'variable_value');
INSERT INTO type VALUES (6, 'term_and');
INSERT INTO type VALUES (7, 'term_or');
INSERT INTO type VALUES (8, 'variable_and');
INSERT INTO type VALUES (9, 'variable_or');
INSERT INTO type VALUES (10, 'variable_not');
